version: "3.7"
services:
  app_viewer:
    image: nginx:latest
    container_name: app_viewer
    ports:
      - 8080:80
    volumes:
      - ./dist:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
